[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via-ir = true

remappings = [
    "@openzeppelin-contracts-5.0.2/=dependencies/@openzeppelin-contracts-5.0.2/",    
    "@openzeppelin-contracts-upgradeable-5.0.2/=dependencies/@openzeppelin-contracts-upgradeable-5.0.2/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
    "forge-std/=dependencies/forge-std-1.9.6/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
