[profile.default]
src = "src"
out = "out"
libs = ["dependencies", "node_modules"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Upgradeable Safety Validations from OpenZeppelin
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=dependencies/forge-std/src/",
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=dependencies/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-foundry-upgrades/=dependencies/openzeppelin-foundry-upgrades/src/"
]


[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"

[rpc_endpoints]
sepolia = "${SEPOLIA_URL}"
base-sepolia = "${BASE_SEPOLIA_URL}"
local-node = "${LOCAL_NODE_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_API_KEY}" }
base-sepolia = { key = "${BASE_SEPOLIA_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
